### ISSUE TITLE
MemNode support

### ISSUE THREAD

**Issue by ekallal** [SystemRDL/PeakRDL-Markdown#12]
adding a mem component into an existing address map results in the following error: 

`warning: Unsupported type of node (MemNode) for <inst_name>`

Isn't this a supported node type which should show up in the address map?  Or am I missing something?

 PeakRDL-regblock will add it into the generated sv with something like this: 

`decoded_reg_strb.<inst_name> = cpuif_req_masked & (cpuif_addr >= 'h2000) & (cpuif_addr <= 'h2000 + 'hf);`

Also, section 13 of the systemRDL spec says "An address component map (addrmap) contains registers, register files, memories, and/or other address maps and assigns a virtual address or final addresses"

**Comment by MarekPikula** [comment]
Hi, indeed, it's supported by SystemRDL itself, but while I was actively developing the Markdown exporter I didn't have enough time to fully support it, so I left a warning that the MemNode is not supported. Mind that it's not supported for Markdown exporter only, not SystemRDL in general.

If you need this in your generated Markdown, feel free to open a PR. It should be relatively simple to implement, but I never got down to properly write and test it.
