### ISSUE TITLE
Can we revise pyproject.toml to point at the current root PeakRDL version?

### ISSUE THREAD

**Issue by ion-concepts** [SystemRDL/PeakRDL-Markdown#7]
Any chance we can update the dependency requirement for peakrdl to the current version 0.8.x?
I did a bit of testing and didn't run into any obvious incompatibilities.

peakrdl = "^0.8.0"

**Comment by MarekPikula** [comment]
Sure, I'll look into it early next week. If you need it sooner, don't hesitate to make a PR.

**Comment by ion-concepts** [comment]
Just submitted #8 for you.

BTW Current `peakrdl` release is now 0.9.0 so modified my original request and PR accordingly.
